services:

  task-blaster-db:
    image: postgres:latest
    container_name: task-blaster-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=TaskBlaster
    volumes:
      - task-blaster-data:/var/lib/postgresql/data
    networks:
      - task-blaster-network

  hangfire-db:
    image: postgres:latest
    container_name: hangfire-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Hangfire
    volumes:
      - hangfire-data:/var/lib/postgresql/data
    networks:
      - task-blaster-network

  task-management-api:
    build:
      context: ./TaskBlaster.TaskManagement
      dockerfile: Dockerfile
    container_name: task-management
    ports:
      - "6060:5212"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5212
      - ConnectionStrings__TaskBlasterDatabaseConnectionString=Host=task-blaster-db;Port=5432;Database=TaskBlaster;Username=admin;Password=admin
    networks:
      - task-blaster-network

  notification-api:
    build:
      context: ./TaskBlaster.TaskManagement.Notifications
      dockerfile: Dockerfile
    container_name: notifications
    ports:
      - "6070:5165"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5165
      - ConnectionStrings__HangfireDatabaseConnectionString=Host=notification-api;Port=5434;Database=Hangfire;Username=admin;Password=admin
    networks:
      - task-blaster-network

networks:
  task-blaster-network:
    driver: bridge

volumes:
  task-blaster-data:
  hangfire-data:
